<a href="https://colab.research.google.com/github/JesusDBS/learning-notes/blob/main/notebooks/00_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This notebook covers the basic usage of tensorflow

Specifically:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up regular Python functions)


## Introduction to Tensors

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.11.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimensions of a vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dim)
matrix = tf.constant([[10, 7],[7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
second_matrix = tf.constant([[10., 7.],[3., 2.], [8., 9.]], dtype=tf.float16) #specify the data type with dtype parameter
second_matrix #The higher the number of precision, the more exact these numbers are stored on your PC

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Lets create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10, 11, 12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What I've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with `tf.Variable`

In [ ]:
changeable_tensor= tf.Variable([10, 7])
unchangeable_tensor= tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Trying to change one of the elements in our changeable tensor
# changeable_tensor[0] = 7

In [ ]:
# Trying with .assign method
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Trying change a value in unchangable tensor
# unchangeable_tensor[0] = 7

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
# Create tow random (but the same) tensors
# Those are actually pseudo random numbers
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect the learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Shuffeling tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other way to make tensors

In [ ]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [ ]:
#You can also turn NumPy arrays into tensors
import numpy as np

#X = tf.constant(some_matrix) #capitl for matrix or tensor
#y = tf.constant(vector) #non-capital for vector

In [ ]:
numpy_A = np.arange(1,25,dtype=np.int32) #Create numpy array between 1 nd 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4)) #The multiplication of 2, 3, and 4 is 24 (the original shape of the vector)
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 2, 2))
A

<tf.Tensor: shape=(2, 3, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16]],

        [[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]], dtype=int32)>

### Getting information from Tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create  rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elemnts in our tensor:", tf.size(rank_4_tensor))
print("Total number of elemnts in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elemnts in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elemnts in our tensor: 120


### Idexing tensors

Tensors can be indexed just like Python lists.

In [ ]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[1, 2, 3, 4],[5, 6, 7, 8]])
rank_2_tensor, rank_2_tensor.ndim, rank_2_tensor.shape

(<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=int32)>, 2, TensorShape([2, 4]))

In [ ]:
# Get the last item of each of row our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 8], dtype=int32)>

In [ ]:
#Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]], dtype=int32)>

In [ ]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basics operations**

`+, -, *, /`

In [ ]:
# you can add values to a tensor using the addition operators
tensor = tf.constant([[10, 7], [3, 4]])
tensor, tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>, 2)

In [ ]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [ ]:
#Matrix multiplication in tensorflow
tensor_1 = tf.constant([1, 2])
tensor_2 = tf.constant([[1, 2],[3, 4]])
tensor_1, tensor_2

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>)

In [ ]:
tensor_1 = tf.expand_dims(tensor_1, axis=0)
tensor_1

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>

In [ ]:
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ 7, 10]], dtype=int32)>

In [ ]:
tensor_1 * tensor_2 #Different kind of multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [3, 8]], dtype=int32)>

In [ ]:
tensor_a = tf.constant([[1, 2, 5],
                        [7, 2, 1],
                        [3, 3, 3]])
tensor_b = tf.constant([[3, 5],
                        [6, 7],
                        [1, 8]])
tensor_a, tensor_b

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [ ]:
tf.matmul(tensor_a, tensor_b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
tensor_a @ tensor_b #@ in python is used for matrix multiplication

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Create a tensor with shape (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Create another tensor with shape (3, 2)
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

**You can´t multiply matrices with mistmatching dimensions!**

In [ ]:
# Changing the Y dimensions
Y_h = tf.reshape(Y, shape=(2, 3))
Y_h

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
X.shape, tf.reshape(Y, shape=(2, 3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
X @ Y_h

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# tf.matmul(X, Y)

In [ ]:
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# We can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred as dot np.product

you can perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Check the value of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed to (2, 3):")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed to (2, 3):
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


**Generally when performing matrix multiplication if one of them doesn't line up, transpose one of them will be needed to satisfy the dot product rules**

### Changing the datatype of a tensor

In [ ]:
tf.__version__

'2.11.0'

In [ ]:
#Create a new tensor with default dtype float.32
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision, less memory)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.int16)
E

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 7, 10], dtype=int16)>

### Aggregatin tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregtion:
* Get the minimun
* Get the maximun
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([78, 43, 95, 40, 81, 95, 97, 11, 32, 88, 47, 62, 21, 71, 40, 61, 30,
       17,  0, 80, 76, 64, 91, 50, 66, 13, 12, 34, 77, 85, 22, 82, 77, 64,
       90, 32, 69, 67, 44, 19, 65, 79, 82, 24, 55, 14,  8, 20, 12, 69])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#Find the minimun
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
#Find the maximun
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
#Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=53>

In [ ]:
#Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2651>

In [ ]:
#Find the variance
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=804>

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=804.45953>

In [ ]:
#Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.362995>

### Find the positional maximum and minimum

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3] #could be red, gree, blue, pruple
depth = 4
tf.one_hot(some_list, depth=depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, depth=depth, on_value='ON', off_value='OFF')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>

### Squaring, log, square root

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

### Tensors and NumPy

Tensorflow interacts beautifully win NumPy arrays

In [ ]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Convert tensor back to numpy array
np.array(J)

array([ 3.,  7., 10.])

In [ ]:
J.numpy()

array([ 3.,  7., 10.])

In [ ]:
# The default types of each are sightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [ ]:
tf.test.is_gpu_available()

False

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
tf.config.list_physical_devices('GPU')

[]

In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



### 00 Tensorflow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant().`

In [ ]:
s = tf.constant(8)
v = tf.constant([10, 20, 30])
M = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
T = tf.constant([[[1, 2, 3],
                 [4, 5, 6]],

                 [[7, 8, 9],
                 [10, 11, 12]],

                 [[13, 14, 15],
                  [16, 17, 18]]])
print("This is a scalar:")
print(s,"\n")

print("This is a vector:")
print(v,"\n")

print("This is a matrix")
print(M, "\n")

print("This is Tensor")
print(T, "\n")

This is a scalar:
tf.Tensor(8, shape=(), dtype=int32) 

This is a vector:
tf.Tensor([10 20 30], shape=(3,), dtype=int32) 

This is a matrix
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) 

This is Tensor
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32) 



2. Find the shape, rank and size of the tensors you created in 1.

In [ ]:
def properties_pretty_printed(T: tf.Tensor, nl=False):
  print("This is the shape of the Tensor: ", T.shape)
  print("This is the rank of the Tensor: ", T.ndim)
  print("This is the size of the Tensor: ", tf.size(T))

  if nl:
    print("\n")

def print_by_list(tensor_list: list):
  if not isinstance(tensor_list, list):
    tensor_list = [tensor_list]

  for n, tensor in enumerate(tensor_list):
    if isinstance(tensor, tf.Tensor):
      if n == len(tensor_list)-1:
        properties_pretty_printed(tensor)
      else:
        properties_pretty_printed(tensor, nl=True)
    else:
      raise TypeError("All the elements of the list must be tensors")

In [ ]:
tensor_list = [s, v, M, T,]
print_by_list(tensor_list)

This is the shape of the Tensor:  ()
This is the rank of the Tensor:  0
This is the size of the Tensor:  tf.Tensor(1, shape=(), dtype=int32)


This is the shape of the Tensor:  (3,)
This is the rank of the Tensor:  1
This is the size of the Tensor:  tf.Tensor(3, shape=(), dtype=int32)


This is the shape of the Tensor:  (2, 3)
This is the rank of the Tensor:  2
This is the size of the Tensor:  tf.Tensor(6, shape=(), dtype=int32)


This is the shape of the Tensor:  (3, 2, 3)
This is the rank of the Tensor:  3
This is the size of the Tensor:  tf.Tensor(18, shape=(), dtype=int32)


3. Create two tensors containing random values between 0 and 1 with shape `[5, 300].`

In [ ]:
tensor_random_1 = tf.random.Generator.from_seed(42)
tensor_random_1 = tensor_random_1.uniform(shape=(5, 300))
tensor_random_2 = tf.random.Generator.from_seed(42)
tensor_random_2 = tensor_random_2.uniform(shape=(5, 300))
print("This is tensor 1:")
print(tensor_random_1, "\n")
print("This is tensor 2:")
print(tensor_random_2, "\n")

This is tensor 1:
tf.Tensor(
[[0.7493447  0.73561966 0.45230794 ... 0.5816356  0.5627874  0.7491298 ]
 [0.6438937  0.6938418  0.04408407 ... 0.04825139 0.5099728  0.26470542]
 [0.21373153 0.6683699  0.78474844 ... 0.19658887 0.22030771 0.3766911 ]
 [0.68190825 0.29304636 0.5415933  ... 0.37111604 0.76053166 0.7538099 ]
 [0.8011551  0.48830473 0.13867617 ... 0.20301867 0.8378159  0.19984365]], shape=(5, 300), dtype=float32) 

This is tensor 2:
tf.Tensor(
[[0.7493447  0.73561966 0.45230794 ... 0.5816356  0.5627874  0.7491298 ]
 [0.6438937  0.6938418  0.04408407 ... 0.04825139 0.5099728  0.26470542]
 [0.21373153 0.6683699  0.78474844 ... 0.19658887 0.22030771 0.3766911 ]
 [0.68190825 0.29304636 0.5415933  ... 0.37111604 0.76053166 0.7538099 ]
 [0.8011551  0.48830473 0.13867617 ... 0.20301867 0.8378159  0.19984365]], shape=(5, 300), dtype=float32) 



4. Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
tensor_random_1 @ tf.transpose(tensor_random_2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[101.66054 ,  73.4119  ,  75.69495 ,  77.3254  ,  76.02343 ],
       [ 73.4119  ,  96.01821 ,  68.701004,  71.45271 ,  74.41574 ],
       [ 75.69495 ,  68.701004,  97.2023  ,  75.038734,  72.08196 ],
       [ 77.3254  ,  71.45271 ,  75.038734,  98.26957 ,  74.205154],
       [ 76.02343 ,  74.41574 ,  72.08196 ,  74.205154,  99.33444 ]],
      dtype=float32)>

In [ ]:
tf.matmul(tensor_random_1, tf.transpose(tensor_random_1))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[101.66054 ,  73.4119  ,  75.69495 ,  77.3254  ,  76.02343 ],
       [ 73.4119  ,  96.01821 ,  68.701004,  71.45271 ,  74.41574 ],
       [ 75.69495 ,  68.701004,  97.2023  ,  75.038734,  72.08196 ],
       [ 77.3254  ,  71.45271 ,  75.038734,  98.26957 ,  74.205154],
       [ 76.02343 ,  74.41574 ,  72.08196 ,  74.205154,  99.33444 ]],
      dtype=float32)>

In [ ]:
tensor_random_1 * tensor_random_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.5615175 , 0.54113626, 0.20458247, ..., 0.33829996, 0.31672966,
        0.56119543],
       [0.41459912, 0.48141646, 0.00194341, ..., 0.0023282 , 0.26007226,
        0.07006896],
       [0.04568117, 0.4467183 , 0.6158301 , ..., 0.03864719, 0.04853548,
        0.14189619],
       [0.46499887, 0.08587617, 0.2933233 , ..., 0.13772711, 0.5784084 ,
        0.56822944],
       [0.64184946, 0.23844151, 0.01923108, ..., 0.04121658, 0.70193547,
        0.03993748]], dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [ ]:
tf.tensordot(tensor_random_1, tf.transpose(tensor_random_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[101.66054 ,  73.4119  ,  75.69495 ,  77.3254  ,  76.02343 ],
       [ 73.4119  ,  96.01821 ,  68.701004,  71.45271 ,  74.41574 ],
       [ 75.69495 ,  68.701004,  97.2023  ,  75.038734,  72.08196 ],
       [ 77.3254  ,  71.45271 ,  75.038734,  98.26957 ,  74.205154],
       [ 76.02343 ,  74.41574 ,  72.08196 ,  74.205154,  99.33444 ]],
      dtype=float32)>

Create a tensor with random values between 0 and 1 with shape `[224, 224, 3].`

In [ ]:
tensor_random_3 = tf.random.Generator.from_seed(42)
tensor_random_3 = tensor_random_3.uniform(shape=(224, 224, 3))
tensor_random_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7493447 , 0.73561966, 0.45230794],
        [0.49039817, 0.1889317 , 0.52027524],
        [0.8736881 , 0.46921718, 0.63932586],
        ...,
        [0.8035464 , 0.8265822 , 0.84540355],
        [0.16108847, 0.48667014, 0.6170937 ],
        [0.22355545, 0.93454087, 0.5319209 ]],

       [[0.7508148 , 0.46019256, 0.14229465],
        [0.10500956, 0.72874916, 0.89662087],
        [0.85220826, 0.76973283, 0.11408448],
        ...,
        [0.38387823, 0.72712064, 0.7561674 ],
        [0.70352066, 0.22680473, 0.24423313],
        [0.39240444, 0.32533252, 0.39407527]],

       [[0.74291146, 0.54543686, 0.32094967],
        [0.6671035 , 0.8900143 , 0.64271927],
        [0.5317905 , 0.21345353, 0.71189904],
        ...,
        [0.53968227, 0.7233304 , 0.7900686 ],
        [0.99334645, 0.857829  , 0.67977047],
        [0.8087704 , 0.06597769, 0.62171316]],

       ...,

       [[0.84861326, 0.6271888 , 0.7023717 ],
        [0.46

In [ ]:
tensor_random_3[0]

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[7.49344707e-01, 7.35619664e-01, 4.52307940e-01],
       [4.90398169e-01, 1.88931704e-01, 5.20275235e-01],
       [8.73688102e-01, 4.69217181e-01, 6.39325857e-01],
       [6.46711707e-01, 9.62467551e-01, 4.10091639e-01],
       [8.65407467e-01, 8.86297822e-01, 2.77957320e-01],
       [8.85776281e-01, 2.17984200e-01, 2.91151166e-01],
       [3.95386219e-02, 8.13679099e-01, 8.13985229e-01],
       [5.21806836e-01, 1.24969244e-01, 5.48848271e-01],
       [7.75577307e-01, 6.18440270e-01, 2.49362230e-01],
       [8.93418431e-01, 2.84228444e-01, 7.03326464e-01],
       [2.62213707e-01, 4.43216205e-01, 4.66464996e-01],
       [5.98187447e-02, 4.00982022e-01, 6.92923546e-01],
       [1.28468394e-01, 2.27703691e-01, 3.36912155e-01],
       [5.32913804e-01, 5.91432571e-01, 2.17382431e-01],
       [5.32207489e-01, 5.14833927e-02, 3.95141840e-02],
       [4.18668747e-01, 7.89399147e-01, 4.38427925e-02],
       [9.69558358e-01, 4.91161823e-01

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [ ]:
tf.reduce_max(tensor_random_3, axis=0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.99618435, 0.98762584, 0.9980433 ],
       [0.9952135 , 0.99883556, 0.99686027],
       [0.9946785 , 0.99178827, 0.9999734 ],
       [0.98847675, 0.9987333 , 0.99251914],
       [0.99908113, 0.99813354, 0.9987514 ],
       [0.9995972 , 0.9918057 , 0.9936507 ],
       [0.996528  , 0.99225354, 0.99470997],
       [0.9992938 , 0.998433  , 0.9907274 ],
       [0.99991727, 0.9985622 , 0.9995769 ],
       [0.9973265 , 0.9939188 , 0.98792326],
       [0.99959576, 0.9974675 , 0.9745352 ],
       [0.98768175, 0.99975455, 0.98718727],
       [0.99806726, 0.999974  , 0.9972402 ],
       [0.9985361 , 0.99618876, 0.9912269 ],
       [0.99842477, 0.99512637, 0.9981767 ],
       [0.9973539 , 0.99861526, 0.99648666],
       [0.98746395, 0.9944526 , 0.9986727 ],
       [0.99964285, 0.99563706, 0.99757504],
       [0.9980036 , 0.99927306, 0.99555767],
       [0.98547363, 0.99981403, 0.98033845],
       [0.9992262 , 0.99628043, 0.9895811 ],
     

8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3].`

In [ ]:
tensor_random_4 = tf.random.Generator.from_seed(42)
tensor_random_4 = tensor_random_4.uniform(shape=(1, 224, 224, 3))
print("This is tensor 4:")
print(tensor_random_4, "\n")
print_by_list(tensor_random_4)

This is tensor 4:
tf.Tensor(
[[[[0.7493447  0.73561966 0.45230794]
   [0.49039817 0.1889317  0.52027524]
   [0.8736881  0.46921718 0.63932586]
   ...
   [0.8035464  0.8265822  0.84540355]
   [0.16108847 0.48667014 0.6170937 ]
   [0.22355545 0.93454087 0.5319209 ]]

  [[0.7508148  0.46019256 0.14229465]
   [0.10500956 0.72874916 0.89662087]
   [0.85220826 0.76973283 0.11408448]
   ...
   [0.38387823 0.72712064 0.7561674 ]
   [0.70352066 0.22680473 0.24423313]
   [0.39240444 0.32533252 0.39407527]]

  [[0.74291146 0.54543686 0.32094967]
   [0.6671035  0.8900143  0.64271927]
   [0.5317905  0.21345353 0.71189904]
   ...
   [0.53968227 0.7233304  0.7900686 ]
   [0.99334645 0.857829   0.67977047]
   [0.8087704  0.06597769 0.62171316]]

  ...

  [[0.84861326 0.6271888  0.7023717 ]
   [0.46894228 0.4787085  0.1912539 ]
   [0.39595473 0.5948347  0.6859689 ]
   ...
   [0.55004704 0.81996536 0.6626886 ]
   [0.30092347 0.3980503  0.17080736]
   [0.9393351  0.3430456  0.15847623]]

  [[0.07707131 0

In [ ]:
tf.squeeze(tensor_random_4)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7493447 , 0.73561966, 0.45230794],
        [0.49039817, 0.1889317 , 0.52027524],
        [0.8736881 , 0.46921718, 0.63932586],
        ...,
        [0.8035464 , 0.8265822 , 0.84540355],
        [0.16108847, 0.48667014, 0.6170937 ],
        [0.22355545, 0.93454087, 0.5319209 ]],

       [[0.7508148 , 0.46019256, 0.14229465],
        [0.10500956, 0.72874916, 0.89662087],
        [0.85220826, 0.76973283, 0.11408448],
        ...,
        [0.38387823, 0.72712064, 0.7561674 ],
        [0.70352066, 0.22680473, 0.24423313],
        [0.39240444, 0.32533252, 0.39407527]],

       [[0.74291146, 0.54543686, 0.32094967],
        [0.6671035 , 0.8900143 , 0.64271927],
        [0.5317905 , 0.21345353, 0.71189904],
        ...,
        [0.53968227, 0.7233304 , 0.7900686 ],
        [0.99334645, 0.857829  , 0.67977047],
        [0.8087704 , 0.06597769, 0.62171316]],

       ...,

       [[0.84861326, 0.6271888 , 0.7023717 ],
        [0.46

10. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [ ]:
tensor_9 = tf.constant(np.arange(1,11))
print(tensor_9, "\n")
print_by_list(tensor_9)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int64) 

This is the shape of the Tensor:  (10,)
This is the rank of the Tensor:  1
This is the size of the Tensor:  tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
tf.argmax(tensor_9), tensor_9[tf.argmax(tensor_9)]

(<tf.Tensor: shape=(), dtype=int64, numpy=9>,
 <tf.Tensor: shape=(), dtype=int64, numpy=10>)

10. One-hot encode the tensor you created in 9.

In [ ]:
print("This is the original tensor:")
print(tensor_9, "\n")
print("This is the tensor encoded:")
tf.one_hot(tensor_9, depth=tf.size(tensor_9).numpy())

This is the original tensor:
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int64) 

This is the tensor encoded:


<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>